
/* Drop Tables */

DROP TABLE T_SENSOR_SETTINGS;
DROP TABLE T_LOCATION_SETTINGS;
DROP TABLE M_USER;




/* Create Tables */

CREATE TABLE M_USER
(
	USER_SEQ INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	USER_NAME TEXT,
	CREATE_USER TEXT NOT NULL,
	CREATE_DATE TEXT NOT NULL,
	UPDATE_USER TEXT,
	UPDATE_DATE TEXT,
	DELETE_USER TEXT,
	DELETE_DATE TEXT,
	DELETE_FLG INTEGER NOT NULL
);


-- 登録した位置情報を保持
CREATE TABLE T_LOCATION_SETTINGS
(
	LOCATION_SEQ INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	LOCATION_NAME TEXT,
	ADDRESS TEXT,
	LAT REAL,
	LON REAL,
	RANGE INTEGER,
	USER_SEQ INTEGER NOT NULL UNIQUE,
	CREATE_USER TEXT NOT NULL,
	CREATE_DATE TEXT NOT NULL,
	UPDATE_USER TEXT,
	UPDATE_DATE TEXT,
	DELETE_USER TEXT,
	DELETE_DATE TEXT,
	DELETE_FLG INTEGER NOT NULL,
	FOREIGN KEY (USER_SEQ)
	REFERENCES M_USER (USER_SEQ)
);


-- 登録したセンサ情報を保持
CREATE TABLE T_SENSOR_SETTINGS
(
	LOCATION_SEQ INTEGER NOT NULL UNIQUE,
	WIFI_FLG INTEGER DEFAULT 0 NOT NULL,
	WIFI_TETHERING_FLG INTEGER DEFAULT 0 NOT NULL,
	MANNER_MODE_FLG INTEGER DEFAULT 0 NOT NULL,
	VOLUME INTEGER DEFAULT 0 NOT NULL,
	BT_FLG INTEGER DEFAULT 0 NOT NULL,
	GPS_FLG INTEGER DEFAULT 0 NOT NULL,
	MOBILE_NETWORK_FLG INTEGER DEFAULT 0 NOT NULL,
	CREATE_USER TEXT NOT NULL,
	CREATE_DATE TEXT NOT NULL,
	UPDATE_USER TEXT,
	UPDATE_DATE TEXT,
	DELETE_USER TEXT,
	DELETE_DATE TEXT,
	DELETE_FLG INTEGER NOT NULL,
	FOREIGN KEY (LOCATION_SEQ)
	REFERENCES T_LOCATION_SETTINGS (LOCATION_SEQ)
);



